package uk.gov.dluhc.notificationsapi.database.entity

enum class NotificationType {
    APPLICATION_RECEIVED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    PHOTO_RESUBMISSION,
    ID_DOCUMENT_RESUBMISSION,
    ID_DOCUMENT_REQUIRED,
    REJECTED_DOCUMENT,
    NINO_NOT_MATCHED,
    REJECTED_PARENT_GUARDIAN,
    REJECTED_PREVIOUS_ADDRESS,
    PARENT_GUARDIAN_PROOF_REQUIRED,
    PREVIOUS_ADDRESS_DOCUMENT_REQUIRED,
    BESPOKE_COMM,
    NOT_REGISTERED_TO_VOTE,
    SIGNATURE_RESUBMISSION,
    SIGNATURE_RECEIVED,

    // Legacy communications - no longer sent.
    REJECTED_SIGNATURE,
    REQUESTED_SIGNATURE,
}
