version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    assignees:
      - "aleyipsoftwire"
    # Only create PRs for direct dependencies
    allow:
      - dependency-type: "direct"
    # Ignore libs-api dependencies
    ignore:
      - dependency-name: "uk.gov.dluhc*"
    groups:
      # Group all gradle security updates
      gradle-security-updates:
        applies-to: security-updates
        patterns: [ "*" ]
      # Group all kotlin plugin updates
      kotlin-plugins:
        patterns:
          - "jvm"
          - "kapt"
          - "plugin.allopen"
          - "plugin.jpa"
          - "plugin.spring"
      # Group all version updates, except for Spring Boot and the dependency checker
      gradle-version-updates:
        applies-to: version-updates
        patterns: [ "*" ]
        exclude-patterns:
          - "org.springframework.boot"
          - "org.owasp.dependencycheck"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    assignees:
      - "aleyipsoftwire"
    groups:
      # Group all github-action updates
      github-actions:
        applies-to: version-updates
        patterns: [ "*" ]

  - package-ecosystem: "npm"
    directory: "templates"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    assignees:
      - "aleyipsoftwire"
    ignore:
      # Node.js versions should always be manually updated
      - dependency-name: "@types/node"
    groups:
      # Group all lambda npm security updates
      templates-security-updates:
        applies-to: security-updates
        patterns: [ "*" ]
      # These updates should be done as a group
      typescript:
        patterns: [ "typescript", "tsx" ]
      jest:
        patterns: [ "jest", "ts-jest", "@types/jest" ]
      # Group all lambda npm version updates
      templates-version-updates:
        applies-to: version-updates
        patterns: [ "*" ]
        update-types: [ "minor", "patch" ]
    open-pull-requests-limit: 20
