name: Run todo checker
on:
  push:
    branches:
      - main
      - EIP1-13868-set-up-to-do-checker

jobs:
  check-todos:
    uses: communitiesuk/eip-ero-shared-workflows/.github/workflows/todo-check-with-slack-notify.yml@main
    with:
      exclude-path-regex: (\.github\/workflows\/todo-check-with-slack-notify\.yml)
    secrets: inherit
